# Generated by Django 5.2.7 on 2025-11-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("short_description", models.TextField(verbose_name="Descrição curta")),
                ("description", models.TextField(verbose_name="Descrição completa")),
                (
                    "image",
                    models.ImageField(
                        upload_to="about/", verbose_name="Foto de perfil"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sobre Mim",
                "verbose_name_plural": "Sobre Mim",
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Empresa/Cargo"),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Descricao da experiencia"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="experiences/",
                        verbose_name="Logo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Experiencia",
                "verbose_name_plural": "Experiencia",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Título do projeto"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="projects/", verbose_name="Imagem do projeto"
                    ),
                ),
                (
                    "github_link",
                    models.URLField(blank=True, verbose_name="Link do GitHub"),
                ),
            ],
            options={
                "verbose_name": "Projetos",
            },
        ),
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.TextField(max_length=100, verbose_name="Nome da tecnologia"),
                ),
                ("description", models.TextField(verbose_name="Sobre a tecnologia")),
            ],
            options={
                "verbose_name": "Sobre Mim",
                "verbose_name_plural": "Sobre Mim",
            },
        ),
    ]
